### ISSUE TITLE
Audinarey - pool's `_allocPoint` point will not be updated for a pool if another pool's lp supply is zero

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-sophon-judging#31]
Audinarey

medium

# pool's `_allocPoint` point will not be updated for a pool if another pool's lp supply is zero

## Summary
In order to set the `_allocPoint` for a particular pool in the farming contract, the `owner` calls `SophonFarming::set(...)`. If this call is made with the option (`_withUpdate` = `true`) to update the accounting for all pools, then the `massUpdatePools()` function is called to loop over and update accounting for all pools. 
```solidity
File: SophonFarming.sol
195:     function set(uint256 _pid, uint256 _allocPoint, bool _withUpdate) public onlyOwner {
196:         if (isFarmingEnded()) {
197:             revert FarmingIsEnded();
198:         }
199:  @>     if (_withUpdate) {
200:  @>         massUpdatePools(); // @audit if the is called when the lpSupply of any pool is zero, it will return without updating the parameters

```
The [`massUpdatePools()` function loops](https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L401) over ALL the pools and calls the `updatePool(...)` for each of the pools. However, the `updatePool(...)` function returns and ends execution if it encounters any empty pool without updating the allocation point for the pool of interest even if it's own `lpSupply` is greater than zero.
```solidity
File: SophonFarming.sol
411:     function updatePool(uint256 _pid) public {
412:         PoolInfo storage pool = poolInfo[_pid];
413:         if (getBlockNumber() <= pool.lastRewardBlock) {
414:             return;
415:         }
416:         uint256 lpSupply = pool.amount;
417:         uint256 _pointsPerBlock = pointsPerBlock;
418:         uint256 _allocPoint = pool.allocPoint;
419:  @>     if (lpSupply == 0 || _pointsPerBlock == 0 || _allocPoint == 0) {
420:             pool.lastRewardBlock = getBlockNumber();
421:  @>         return;
422:         }

```

## Vulnerability Detail

- Consider 3 pools lp1, lp2 and lp3 respectively with `lpSupply` 1000lp1, 0lp2, 1000lp3
- admin calls `set(...)` for lp1 to change its `_allocPoint` from 100 to 120
- as seen on `l419` above, the call to `set` will return and end  because the `lpSupply` of lp2 is zero.
- hence the `_allocPoint` of lp1 is not updated to 120

## Impact
- This breaks core protocol functionality as the `lpSupply` of one pool affects core state update of another pool.
- This can also lead to leak of value for the user or the protocol depending on direction of the update (increasing / decreasing) `_allocPoint` value.

## Code Snippet
https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L401-L402

## Tool used

Manual Review

## Recommendation
Modify the `set(...)` function to update only the pool whose allocation point is being set as shown below:

```solidity
File: SophonFarming.sol
195:     function set(uint256 _pid, uint256 _allocPoint, bool _withUpdate) public onlyOwner {
196:         if (isFarmingEnded()) {
197:             revert FarmingIsEnded();
198:         } 

199:   -     if (_withUpdate) {
200:   -         massUpdatePools(); // @audit if the is called
201:   -     }

199:   +     if (_withUpdate) {
200:   +        updatePool(pid)
201:   +     }

```

**Comment by sherlock-admin4** [comment]
2 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because massUpdatePools() will not revert and still update as intended

**0xreadyplayer1** commented:
>  the problem is unclear how lpsupply being zero for lp2 can lead to not updating lp1 ? moreover the recommendation and issue described are unclear

**Comment by Audinarey** [comment]
Escalate


> the problem is unclear how lpsupply being zero for lp2 can lead to not updating lp1 ? moreover the recommendation and issue described are unclear

In my explanantion, I stated that whenever `set(...)` is called for a particular pool, it calls `massUpdatePools(...)`
> The [massUpdatePools() function loops](https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L401) over ALL the pools and calls the `updatePool(...)` for each of the pools

however, the`updatePool(...)` completes execution and returns if it encounters a pool whose `lpSupply` is zero and as such the `pool.allocPoint` is not updated because the call is completed before L209.


```solidity
    function set(uint256 _pid, uint256 _allocPoint, bool _withUpdate) public onlyOwner {
        if (isFarmingEnded()) {
            revert FarmingIsEnded();
        }
        if (_withUpdate) {
            massUpdatePools();
        }

        PoolInfo storage pool = poolInfo[_pid];
        address lpToken = address(pool.lpToken);
        if (lpToken == address(0) || !poolExists[lpToken]) {
            revert PoolDoesNotExist();
        }
        totalAllocPoint = totalAllocPoint - pool.allocPoint + _allocPoint;
 @>     pool.allocPoint = _allocPoint;

        if (getBlockNumber() < pool.lastRewardBlock) {
            pool.lastRewardBlock = startBlock;
        }

        emit Set(lpToken, _pid, _allocPoint);
    }
```


`lpSupply` can be 0 at different times during a market cycle and if admin decides to make changes at this time with , the changes will not be applied.

> moreover the recommendation ... described are unclear

The suggestion is to ensure that the current state of another pool does not affect the pool whose state is being updated

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> 
> > the problem is unclear how lpsupply being zero for lp2 can lead to not updating lp1 ? moreover the recommendation and issue described are unclear
> 
> In my explanantion, I stated that whenever `set(...)` is called for a particular pool, it calls `massUpdatePools(...)`
> > The [massUpdatePools() function loops](https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L401) over ALL the pools and calls the `updatePool(...)` for each of the pools
> 
> however, the`updatePool(...)` completes execution and returns if it encounters a pool whose `lpSupply` is zero and as such the `pool.allocPoint` is not updated because the call is completed before L209.
> 
> 
> ```solidity
>     function set(uint256 _pid, uint256 _allocPoint, bool _withUpdate) public onlyOwner {
>         if (isFarmingEnded()) {
>             revert FarmingIsEnded();
>         }
>         if (_withUpdate) {
>             massUpdatePools();
>         }
> 
>         PoolInfo storage pool = poolInfo[_pid];
>         address lpToken = address(pool.lpToken);
>         if (lpToken == address(0) || !poolExists[lpToken]) {
>             revert PoolDoesNotExist();
>         }
>         totalAllocPoint = totalAllocPoint - pool.allocPoint + _allocPoint;
>  @>     pool.allocPoint = _allocPoint;
> 
>         if (getBlockNumber() < pool.lastRewardBlock) {
>             pool.lastRewardBlock = startBlock;
>         }
> 
>         emit Set(lpToken, _pid, _allocPoint);
>     }
> ```
> 
> 
> `lpSupply` can be 0 at different times during a market cycle and if admin decides to make changes at this time with , the changes will not be applied.
> 
> > moreover the recommendation ... described are unclear
> 
> The suggestion is to ensure that the current state of another pool does not affect the pool whose state is being updated
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Audinarey** [comment]
As a matter of fact the sponsor confirmed it will be fixed, so how come it was still excluded? @ 0xmystery

**Comment by Audinarey** [comment]
This finding is valid and should be tagged reward

**Comment by mystery0x** [comment]
Please see my commented reasoning on https://github.com/sherlock-audit/2024-05-sophon-judging/issues/226 that is similarly related to this report.

**Comment by Audinarey** [comment]
You are mistaking a `return` for a `continue` statement

This is the case of an early `return` issue that breaks core protocol functionality.
the `return` statement COMPLETES the execution of a function call. 
Quite alright ` pool.lastRewardBlock` will be updated but the call end when the `return` is hit hence L315 is never reached in the scenario described in this finding

For reference, copy the following into remix to understand how `return` works in solidity

```solidity
// SPDX-License-Identifier: GPL-3.0

pragma solidity ^0.8.17;

contract Attacker{
    address public pre;
    uint256 public trim;
    
    constructor () {}

    function changeParam() public {
        
        for (uint8 i = 0; i < 3; i++) {
            if (i == 2) {
                return;
            }
        }
        
        pre = address(type(uint160).max);
        trim = 700;
    }

    function getPre() public view returns(address, uint256) {
        return (pre, trim);
    }
}
``` 

Notice that `pre` and `trim` are never updated as long as the `return` is hit in the loop, 

Therefore as explained in this and other separate findings, immediately one of the pools that is being looped over in `massUpdatePools()` has an `lpSuppy` = 0 is encountered, ` pool.lastRewardBlock` is updated and the call completes, but the `pool.allocPoint` is never updated because [this](https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L209) line is never reached.

**Comment by Audinarey** [comment]
Hence this finding is valid, because the implementation of the `SophonFarming::set(...)` function breaks core protocol functionality


I implore you to please read the summary and vulnerability detail sections again.

**Comment by Audinarey** [comment]
You are mistaking a `return` for a `continue` statement

This is the case of an early `return` issue that breaks core protocol functionality.
the `return` statement COMPLETES the execution of a function call. 
Quite alright ` pool.lastRewardBlock` will be updated but the call end when the `return` is hit hence L163 to L186 is never reached in the scenario described in this finding

For reference, copy the following into remix to understand how `return` works in solidity

```solidity
// SPDX-License-Identifier: GPL-3.0

pragma solidity ^0.8.17;

contract Attacker{
    address public pre;
    uint256 public trim;

    uint256[] public supArray;
    

    constructor () {}

    function changeParam() public  {
        supArray[0] = 50;
        supArray[1] = 0;
        supArray[2] = 50;

        for (uint8 i = 0; i < 3; i++) {

            if (supArray[i] == 0) {
                return;
            }
        }
        
        pre = address(type(uint160).max);
        trim = 700;
    }

    function getPre() public view returns(address, uint256) {
        return (pre, trim);
    }
}
``` 

Notice that `pre` and `trim` are never updated as long as one element of  supArray[0] is 0, 

Therefore as explained in this and other separate findings, immediately one of the pools that is being looped over in `massUpdatePools()` has an `lpSuppy` = 0 is encountered, ` pool.lastRewardBlock` is updated and the call completes, but the `allocPoint` is never updated because the [this](https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L209) line is never reached.

**Comment by Audinarey** [comment]
@mystery0x I await your response

**Comment by WangSecurity** [comment]
I believe this issue is almost the same as https://github.com/sherlock-audit/2024-05-sophon-judging/issues/226 where we already agreed, that hitting the `return` would only stop the `updatePool` function and `set ` would continue its execution.

Planning to reject the escalation and leave the issue as it is, since there is no vulnerability.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Audinarey](https://github.com/sherlock-audit/2024-05-sophon-judging/issues/31/#issuecomment-2144146284): rejected

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/sophon-org/farming-contracts/commit/6d117397d57a39a865cee0621cabf9154fb6fd71
