### ISSUE TITLE
ZdravkoHr. - `SophonFarming.set` can be frontrun with a call to `massUpdatePools` distributing rewards based on the old terms

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-sophon-judging#38]
ZdravkoHr.

medium

# `SophonFarming.set` can be frontrun with a call to `massUpdatePools` distributing rewards based on the old terms

## Summary
[SophonFarming.set()](https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L195-L216) updates the percent of the total rewards that a given pool should receive. This can be frontrun by a call to [massUpdatePools()](https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L399C1-L405C6) to distribute the accumulated rewards based on the current terms.
## Vulnerability Detail
Before changing the allocation points of the pool, `set()` optionally makes a call to `massUpdatePools`
```solidity
        if (_withUpdate) {
            massUpdatePools();
        }
```

If `_withUpdate` is set to false, an update won't be triggered, the allocation points percentages will be updated and the already accumulated rewards will be distributed based on the new terms.

However, anyone can frontrun this transaction with a call to `massUpdatePools()`. This will make it as the owner has called `set()` with `_withUpdate = true` and reward will be distributed based on the old terms.

```solidity
    function massUpdatePools() public {
        uint256 length = poolInfo.length;
        for(uint256 pid = 0; pid < length;) {
            updatePool(pid);
            unchecked { ++pid; }
        }
    }
```

## Impact
Unexpected distribution of rewards.

## Code Snippet
https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L195-L216
https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L399C1-L405C6
## Tool used

Manual Review

## Recommendation
This should be carefully rethought. Adding a modifier to massUpdatePools can help, but it does not solve the problem completely because there are other ways to cause a pool update.

**Comment by sherlock-admin4** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because it would require the admin to make a mistake by inputting a false boolean

**Comment by ZdravkoHr** [comment]
Escalate 

@mystery0x the function being called with `false` is not an admin mistake, it' an intended use

**Comment by sherlock-admin3** [comment]
> Escalate 
> 
> @mystery0x the function being called with `false` is not an admin mistake, it' an intended use

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by mystery0x** [comment]
In your described scenario, inputting false would be a mistake because rewards will need to be distributed based on the old terms before introducing the new terms.

That said, inputting false has got its use, e.g. when `getBlockNumber() <= pool.lastRewardBlock` or `lpSupply == 0` for all existing pools. In that case, having `_withUpdate` as `false` would skip `massUpdatePools()` to save on gas. 

So, overall, there's no logic flaw in the function. It's just that the admin will have to be careful with the input of `_withUpdate` with the current design.

**Comment by WangSecurity** [comment]
@mystery0x could you please also clarify:

> when getBlockNumber() <= pool.lastRewardBlock or lpSupply == 0 for all existing pools. In that case, having _withUpdate as false would skip massUpdatePools() to save on gas.

How does it change the fact the issue is still possible? Or do you mean there is no real impact?

And I still quite don't understand why it's a mistake?

> inputting false would be a mistake because rewards will need to be distributed based on the old terms before introducing the new terms

**Comment by mystery0x** [comment]
@WangSecurity To give a better perspective, there're actually numerous other reports saying that both `add()` and `set()` would need to enforce compulsory `massUpdatePools()` regardless of whether or not it's needed just to be sure that all existing pools would first be updated with the existing (old) `totalAllocPoint()`. But, this is not always the case. For example, in `initialize()`, inputting `false` for `_withUpdate` is justifiably okay because there's no need to do any update on an empty array `poolInfo`.

A mistake would be made if inputting `false` when farming has started presumably `lpSupply != 0` for all existing pools. 

In conclusion, these are admin controlled calls and would not qualify for valid H/M.

**Comment by ZdravkoHr** [comment]
As the code is being written, I feel like the purpose of the function is to let the admin choose whether they want to perform an update before changing the terms. What if they want to change the terms for the current distribution? Then they would need to input false

**Comment by WangSecurity** [comment]
As I understand from both of your comments, inputting `false` for `_withUpdate` being a mistake is a logical assumption, and I don't see it as sufficient and objective enough to consider an error. If it would harm users, then yes, by the rules it would agree it's a mistake, but it's not the case and the code works perfectly fine and as intended when admins input `false` for `_withUpdate` at any moment. The problem is that another actor may front-run the admin's call by executing the `massUpdatePool` with a `true` value, leading to the admin's call executing on the new terms regardless of their input value.

Hence, I agree with the escalation, planning to accept it and validate the report. Are there duplicates of this finding?

**Comment by Autosaida** [comment]
I have a different perspective on this escalation. 

> inputting false for _withUpdate being a mistake is a logical assumption, and I don't see it as sufficient and objective enough to consider an error. If it would harm users, 

Yes, it would harm users. First, please refer to #125 and #122. Initially, I considered these issue valid, but due to an "admin mistake," it turned out to be invalid. According to the logic outlined there, after the accumulation of points begins, any `set` and `add` calls must be made with a parameter of `true` to update properly. Otherwise, it would introduce bias to the previous accumulation. Additionally, this issue has been marked as "will fix" and "sponsor confirmed," indicating it's an expected behavior by the team. That is, after the points start accumulating, administrators will always make corresponding updates when using `set` and `add`. Therefore, this escalation doesn't hold. Furthermore, fundamentally, I believe this issue is mistaken. Shouldn't the points be updated when adding a new pool with `add`? Otherwise, it would be illogical and unfair for previous depositors.

**Comment by WangSecurity** [comment]
Firstly, want to clarify this line:

> Additionally, this issue has been marked as "will fix" and "sponsor confirmed," indicating it's an expected behavior by the team

Doesn't it mean the opposite, that if the issue is marked with "will fix" and "sponsor confirmed", then it's not the behaviour the team expects? Of course, remember it doesn't affect the final decision, but want to make sure I'm on track with you.

Secondly, to make sure I understand what would happen if `_withUpdate` is passed as false: if the start point has been at block 5 (just an example) and the `massUpdatePool` has been then called at block 10. Then, at block 15 admin calls `add` with `_withUpdate` set to false, and the `massUpdatePool` isn't called. After it, at block 20 we call `massUpdatePool`, it will consider the new pool, which was added at block 15, as it was live since block 10, not block 15, so there will be unfair rewards distribution and stakers in that pool will get rewards for blocks 10-14 even though it was created at block 15, correct?

**Comment by Autosaida** [comment]
> Doesn't it mean the opposite, that if the issue is marked with "will fix" and "sponsor confirmed", then it's not the behaviour the team expects?

I'm sorry, English isn't my first language, so I'm not entirely clear on this sentence. What I mean is, for issue #125 and other similar issues, those raised about the required parameters for `add` and `set` needing to be set to `true`, rather than being optional parameters as they are now, does the confirmation from the team mean they also agree with that? I've just started auditing, so I'm not quite clear on it. 

> it will consider the new pool, which was added at block 15, as it was live since block 10, not block 15, so there will be unfair rewards distribution and stakers in that pool will get rewards for blocks 10-14 even though it was created at block 15, correct?

You're right, aligning with my thoughts.

**Comment by 0xAadi** [comment]
I have a different observation

The `massUpdatePool()` function accumulates point shares for all pools from the previous accumulation block to the current block in a single operation. It should be called **BEFORE** any updates are made to a pool after farming has started. 

However, it is not necessary to call it before farming begins, as there will be no points to accumulate before the start block. When a user makes a deposit, the `updatePool(poolId)` function will automatically be called to update the point shares for the specific pool involved.

> if the start point has been at block 5 (just an example) and the `massUpdatePool` has been then called at block 10.

The `massUpdatePool` function does not need to be called if there are no changes in the current pools. 

> Then, at block 15 admin calls `add` with `_withUpdate` set to false, and the `massUpdatePool` isn't called

That means existing pools did not accumulated their point shares before a change happened in the current pool system.

If a new pool is created after farming has started, its point share will be calculated from its creation (15th) block, because the `add()` will set the start block of that pool as current block. Please see [line:164 & 178 ](https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L164C1-L178C50) and also the first deposit will update the pools `lastRewardBlock`. Please [see](https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L434)

There is a potential for disparity in point calculations if a new pool is added or updated after farming has started. To avoid this, the admin should call `massUpdatePool()` before making any updates. Otherwise, other pools will use the new `totalAllocPoint` for point calculation instead of the old one. They should accumulate point shares based on the old `totalAllocPoint` from their `lastRewardBlock` to Block 15.



> After it, at block 20 we call `massUpdatePool`, it will consider the new pool, which was added at block 15, as it was live since block 10, not block 15, so there will be unfair rewards distribution and stakers in that pool will get rewards for blocks 10-14 even though it was created at block 15, correct?

I think no, please see [line:164 & 178 ](https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L164C1-L178C50) which uses the current block number as the start block for that particular pool. So it will accumulate points from Block 15 onwards not from Block 10.

In my observation, `add()` and `set()` functions are admin-only, they are designed to add or update pools both before and after the start of farming. If these functions are called before farming begins, the `_withUpdate` parameter will be set to false. If they are used after farming has started, the `_withUpdate` parameter will be set to true.

**Comment by Autosaida** [comment]
@0xAadi is right. Calls to `set` or `add` after the accumulation of points without updating will affect the earnings of other pool depositors. As mentioned in #125, it will impact the points of other pool depositors before that block (for example, if calling to `add` without updating, `totalAllocPoint` will increase, resulting in a decrease in points for other pools in blocks 10-14).
﻿
Therefore, logically speaking, after the accumulation of points, calls to `add` or `set` should always be updated. Hence, this frontrun isn't a valid issue.

**Comment by 0xAadi** [comment]
@Autosaida I agree.

I do not understand how front-running becomes an attack vector in this context. Each user action, such as a deposit, following a front-running `massUpdatePool()`, will update the pool share first with the new values for that induvidual pool like what  `massUpdatePool()` do for the whole pools. I do not believe front-runners can unfairly benefit in this situation.


The purpose of the `massUpdatePool()` function is to forcefully accumulate all the points for the existing pools before a major change in the point calculation.

According to [Sherlock Rule No. 5](https://docs.sherlock.xyz/audits/judging/judging#vii.-list-of-issue-categories-that-are-not-considered-valid)

>5. Admin Input/call validation: Protocol admin is considered to be trusted in most cases, hence issues where
>
>>1. Admin incorrectly enters an input parameter. Example: Make sure interestPerMin > 1 ether as it is an important parameter. This is not a valid issue.

We cannot expect the admin to mistakenly set `_withUpdate` to `false` in the `add()` and `set()` functions after farming has begun.

**Comment by WangSecurity** [comment]
Thank you for these comments, with that, I agree that the correct way would be to input "true" for `_withUpdate` when calling `add` or `set`, and inputting "false" would be a mistake in that sense.

Planning to reject the escalation and leave the issue as it is.

**Comment by 0xAadi** [comment]
> inputting "false" would be a mistake in that sense.

Yes, it is an admin mistake if the farming has already begun.

I believe the protocol uses `_withUpdate` set to `false` to avoid gas costs when calling `add()` or `set()` before the start block (prior to the beginning of farming). At that stage, point accumulation has not yet begun.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [ZdravkoHr](https://github.com/sherlock-audit/2024-05-sophon-judging/issues/38/#issuecomment-2145918638): rejected
