### ISSUE TITLE
ZdravkoHr. - Users are not protected against deposit slippage

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-sophon-judging#42]
ZdravkoHr.

medium

# Users are not protected against deposit slippage

## Summary
The are a lot of reasons why a transaction may stay for a long time in the mempool - low gas provided, network congestion, etc. Users make decision in which pool to deposit based on the `allocPoints` the given pool has. Since these points can change and there is no slippage parameter, users may lose their tokens for rewards that don't satisfy them.

## Vulnerability Detail
Imagine the following scenario:
  - Alice sees a certain pool gets 40% of all rewards so she deposits 10_000 USDC there and decides to boost them all.
  - The Sophon team has made a decision to decrease the % of the pool to 10% by calling [set()](https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L195-L216)
  - The Sophon's transaction is mined before Alice's transaction
  - Alice ends up depositing in a pool which is not profitable for her and since she boosted her whole deposit, it's impossible to withdraw.

>[!NOTE]
> The same is true for `pointsPerBlock` and `boostMultiplier`
  
## Impact
Medium since users lose their tokens forever, but still receive some rewards. 

> [!Warning]
> If the team plans to deactivate reward pools by setting their % to 0, the impact becomes high

## Code Snippet
https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L195-L216

## Tool used

Manual Review

## Recommendation
Add a slippage parameter to the `deposit` function and revert the transaction  `allocPoints`, `pointsPerBlock` or `boostMultiplier` are not a predefined expected value.

**Comment by sherlock-admin4** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because users can always optionally call deposit() by pre-converting DAI/sDAI, ETH/stETH, ETH/eTH at their control

**Comment by ZdravkoHr** [comment]
Escalate

I don't underdtand the provided reason. The issue talks about slippage protection

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> I don't underdtand the provided reason. The issue talks about slippage protection

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by mystery0x** [comment]
Per Sherlock Judging, "An admin action can break certain assumptions about the functioning of the code".

In your case, reducing the pool's allocation point affects not only Alice but all other existing users associated with the pool to seemingly reduce point farming.  This is not considered a valid issue.

**Comment by WangSecurity** [comment]
Agree with the lead judge, I believe this rule about TRUSTED admins should apply here:

> An admin action can break certain assumptions about the functioning of the code. Example: Pausing a collateral causes some users to be unfairly liquidated or any other action causing loss of funds. This is not considered a valid issue.

Hence, planning to reject the escalation and leave the issue as it is.

**Comment by ZdravkoHr** [comment]
This issue is not about owners screwing users on purpose. In the example from the rules it's expected that some users will be liquidated if the collateral is paused.

This issue shows how users may deposit their funds at unfavorable terms because there is no slippage protection. It can happen because of transaction ordering. It's a low probability with high impact.

**Comment by WangSecurity** [comment]
I didn't say that it's about screwing users on purpose, excuse me if it seemed so. The only described scenario in this report is:
1. The user submits txn expecting the protocol to function in one way.
2. The admin submits txn will break this user's assumption about the functioning of the code (decreasing reward allocation).
3. The user suffers a loss.

I believe it falls down this rule. Of course, no one says it's screwing users on purpose, it can happen unintentionally, but the problem is that the TRUSTED admin's actions leading to the user losing funds is invalid.

The decision remains the same, planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [ZdravkoHr](https://github.com/sherlock-audit/2024-05-sophon-judging/issues/42/#issuecomment-2145928208): rejected
