### ISSUE TITLE
Audinarey - Exchanging ETH for `stETH` during deposit is made at a loss due to missing slippage checks

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-sophon-judging#58]
Audinarey

high

# Exchanging ETH for `stETH` during deposit is made at a loss due to missing slippage checks

## Summary
The lack of slippage control for `submit(...)` function can lead to a loss of assets (yield) and points for the affected users.

## Vulnerability Detail
User call `SophonFarming::depositWeth(...)` with the `_predefinedPool` set as `PredefinedPool.wstETH` to make deposit into a LIDO `stETH/ETH` pool in exchange for the `stETH` tokens by calling `_ethTOstEth(...)` which makes an external call the LIDO `submit(...)` which then cached the `stETH` amount returned in the `_finalAmount` variable. 

```solidity
File: SophonFarming.sol
808:     function _ethTOstEth(uint256 _amount) internal returns (uint256) {
809:         // submit function does not return exact amount of stETH so we need to check balances
810:         uint256 balanceBefore = IERC20(stETH).balanceOf(address(this));
811:   @>    IstETH(stETH).submit{value: _amount}(address(this));
812:         return (IERC20(stETH).balanceOf(address(this)) - balanceBefore);
813:     }

```
However, it is a known fact that the LIDO `stETH/ETH` pool does not exchange ETH for stETH at a 1:1 ratio and historical data has shown that the pool has deppeged by up to 1.4% as shown in this [Chainlink price history data](https://docs.google.com/spreadsheets/d/1PZKBAV7rhxJBa4xKwnobTt8KpauLOK31RLnHTGB4JO8/edit?usp=sharing). As you can see stETH has had periods of wild fluctuations the highest in 2023 reaching a Depeg of over 1.3%
Having said that, the amount of `stETH` tokens recieved will vary (smaller than expected)

In a nutshell, the `submit(...)` function lacks the slippage control that allows the users to revert if the minimum amount amount of `stETH` they received is less than the amount they expected to deposit and earn points for.

- Alice deposits 100wETH (indicating `_boostAmount` = 0 with the intent of increaseing boost after deposit) but the `submit(...)`  function returns 98.9stETH as her investment.
- she later calls `increaseBoost(...)` with the max amount of boost she can get, she will loose a yield and points worth 1.1ETH cummulative. 
- 100wETH of deposit will not give 100stETH worth of returns to Alice

## Impact
Users deposit into the LIDO stETH/ETH pool without slippage checks leading to loss of funds

Likelyhood = High
Impact = High

## Code Snippet
https://github.com/sherlock-audit/2024-05-sophon/blob/main/farming-contracts/contracts/farm/SophonFarming.sol#L808-L813

## Tool used

Manual Review

## Recommendation
- Check the pool and see if it's cheaper to buy stETH from it
- Or add a slippage check to the `_ethTOstEth(...)` function
- Or refactor the code to only use stETH which avoids single sided exposure which creates further issues in the protocol

**Comment by sherlock-admin3** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xmystery** commented:
>  invalid because users can always optionally call deposit() by pre-converting DAI/sDAI, ETH/stETH, ETH/eTH at their control

**Comment by Audinarey** [comment]
Escalate


I agree users can call other functions at their disposal, but your conclusion does not consider 
- that users who already chose the route in this vulnerability will loose their funds without being given the chance to switch to another route as the deposit would be made without reverting because the protocol does not implement a slippage protection to ensure users chose the path of least resistance
- the loss incurred herein is not due to user mistake but missing slippage protection as I suggested in the Recommendation section.


Just out of curiosity are suggesting that the `SophonFarming::depositEth(...)` function is broken and as such, users can use other ?

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> 
> I agree users can call other functions at their disposal, but your conclusion does not consider 
> - that users who already chose the route in this vulnerability will loose their funds without being given the chance to switch to another route as the deposit would be made without reverting because the protocol does not implement a slippage protection to ensure users chose the path of least resistance
> - the loss incurred herein is not due to user mistake but missing slippage protection as I suggested in the Recommendation section.
> 
> 
> Just out of curiosity are suggesting that the `SophonFarming::depositEth(...)` function is broken and as such, users can use other ?

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Audinarey** [comment]
go to #63 for more details on this considering it’s a duplicate to this report

**Comment by Kirkeelee** [comment]
If this issue gets rewarded, then mine should, too. Please check [188](https://github.com/sherlock-audit/2024-05-sophon-judging/issues/188).

**Comment by mystery0x** [comment]
Please see #3 and #67 for commented reasonings similarly related to this report.

#63 describes a different scenario where `_stEthTOwstEth(_amount)` would revert due to the contract receiving 1-2 wei lesser amount of `stETH` via `IERC20(stETH).safeTransferFrom()`.

**Comment by Mayowa002** [comment]
Issue https://github.com/sherlock-audit/2024-05-sophon-judging/issues/45 clearly explains how steth has so previously de-peged. Ideally when other protocols who previously have tried to convert from eth to steth there’s always a slippage protection for the stated reason above. Except loss of funds is no longer counted in Sherlock rules.

**Comment by Audinarey** [comment]
@mystery0x 

- the depegging seems to happen frequently and the loss is substantial
- there is no way for the user to know about this because the loss would not be averted due to the Sophon implementation's missing slippage check


#58, #67, #62, #65, #206 describes that due to a quite regular price deviation occurence, substantial loss is inevitable and suggests a protection mechanism for the users to explore other routes for farming in the protocol. Even a 1% deviation can lead to significant loss for user who invests say 100ETH. which is valid considering that by sherlock rule loss of funds is valid.


I have pointed out that a slippage protection would protect users and ensure they explore other routes of the protocol

**Comment by WangSecurity** [comment]
The staking is made on the staking contract itself at the conversion rate of 1:1, it's not traded. Hence, this issue is not susceptible to slippage cause it's always 1:1. Moreover, the assets are not pegged to each other, they're correlated, but not pegged, hence, the price shouldn't be the same.


Unless this assumption is broken with a coded POC, planning to reject the escalation and leave the issue as it is.

**Comment by Mayowa002** [comment]
Firstly eth to steth is not 1:1. The slippage comes in when 1eth is worth way less steth than expected. Which happens when steth depegs.  Issue https://github.com/sherlock-audit/2024-05-sophon-judging/issues/45 has some info as well concerning this.

**Comment by WangSecurity** [comment]
stETH is not pegged to ETH. It's correlated but not pegged, it's a different asset with its own price. Secondly, as seen in the code it's not bought on a secondary market or somewhere else, it's staked directly on a staking contract, which as I understand exchanges it 1:1. If it's not, please provide sufficient proof, as it was said in the previous message.

Decision remains the same, reject the escalation and leave the issue as it is.

**Comment by Mayowa002** [comment]
There’s no way the protocol would be giving 1:1 of a token they don’t own.. if 1eth = 0.95 steth externally … why would the protocol give 1:1 when they don’t own steth….  

Eth to weth  trades at 1:1 externally so it makes sense if the staking is 1:1

**Comment by WangSecurity** [comment]
I see the logic in your words, but as I've said above, I need concrete evidence that it indeed doesn't exchange them 1:1 (either show the code of external protocols where Sophon stakes or make a coded POC).

Otherwise, the decision remains the same, planning to reject the escalation and leave the issue as it is.

**Comment by Mayowa002** [comment]
protocol makes uses of the submit function of `steth` as shown here [here](https://github.com/sherlock-audit/2024-05-sophon/blob/05059e53755f24ae9e3a3bb2996de15df0289a6c/farming-contracts/contracts/farm/SophonFarming.sol#L811). 

This is what the submit function does on main net

```solidity
function submit(address _referral) external payable returns (uint256) {
        return _submit(_referral);
    }
```

```solidity

  function _submit(address _referral) internal returns (uint256) {
        require(msg.value != 0, "ZERO_DEPOSIT");

        StakeLimitState.Data memory stakeLimitData = STAKING_STATE_POSITION.getStorageStakeLimitStruct();
        // There is an invariant that protocol pause also implies staking pause.
        // Thus, no need to check protocol pause explicitly.
        require(!stakeLimitData.isStakingPaused(), "STAKING_PAUSED");

        if (stakeLimitData.isStakingLimitSet()) {
            uint256 currentStakeLimit = stakeLimitData.calculateCurrentStakeLimit();

            require(msg.value <= currentStakeLimit, "STAKE_LIMIT");

            STAKING_STATE_POSITION.setStorageStakeLimitStruct(stakeLimitData.updatePrevStakeLimit(currentStakeLimit - msg.value));
        }

        uint256 sharesAmount = getSharesByPooledEth(msg.value);

        _mintShares(msg.sender, sharesAmount);

        _setBufferedEther(_getBufferedEther().add(msg.value));
        emit Submitted(msg.sender, msg.value, _referral);

        _emitTransferAfterMintingShares(msg.sender, sharesAmount);
        return sharesAmount;
    }
```
this indicates amounted minted will not be 1:1..

the steth address is at `0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84`
the implementation address is at `0x17144556fd3424EDC8Fc8A4C940B2D04936d17eb`

**Comment by WangSecurity** [comment]
Thank you very much! Got confused by the sponsor's comment #3 that they always exchange 1:1. Indeed the exchange rate is based on the total stETH minted and total ETH in the pool. But, this report talks about the depegging of stETH. Unfortunately, this cannot happen, cause stETH is not pegged to ETH in the first place. Hence, this report lacks a valid path or scenario that would cause issues due to slippage checks.

The decision remains the same, reject the escalation and leave the issue as it is.

**Comment by the-first-elder** [comment]
The swap is eth to steth, when steth looses its value as it does often, as stated in the report has it not depeged??  

This is a simple yet obvious bug that you making more complicated than it seems

**Comment by WangSecurity** [comment]
@the-first-elder as I've said above, stETH is **not** pegged to ETH, hence, it cannot depeg. It's correlated to ETH, but not pegged and if it loses value, but ETH doesn't, it's a normal situation and it cannot be called "depegged".

The decision remains the same, reject the escalation and invalidate the report.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Audinarey](https://github.com/sherlock-audit/2024-05-sophon-judging/issues/58/#issuecomment-2144049975): rejected
